#!/usr/bin/env python3
"""Add a unit-test target to BabyTreat.xcodeproj.

The project has no test target: it was generated by Tuist, where one is a line
in Project.swift, and Tuist is retired (D-13). This does the same job directly
on the .xcodeproj so `xcodebuild test` works.

Idempotent — running it twice is a no-op. Validates with plutil and leaves the
file untouched if anything fails.
"""
import hashlib
import re
import subprocess
import sys

PROJ = "BabyTreat.xcodeproj/project.pbxproj"
SCHEME = "BabyTreat.xcodeproj/xcshareddata/xcschemes/BabyTreat.xcscheme"

TARGET_NAME = "BabyTreatTests"
SOURCES = ["OpenFoodFactsTests.swift"]

# Existing objects the new target has to attach to.
PROJECT_OBJ = "7768D36F9400F21BC1C1A5FC"
APP_TARGET = "E5BE074951FF4B51E71B9FF5"
MAIN_GROUP = "6D03373FE6FF55F3DFBA7FB0"
PRODUCTS_GROUP = "3EF636CB7D1427CA521BA65B"
DEVELOPMENT_TEAM = "47SD75X688"


def oid(seed):
    return hashlib.sha1(("babytreat-tests:" + seed).encode()).hexdigest()[:24].upper()


def insert_before(src, marker, text):
    if marker not in src:
        raise SystemExit(f"marker not found: {marker}")
    return src.replace(marker, text + marker, 1)


def build_settings(config):
    return f"""\t\t{oid("config:" + config)} /* {config} */ = {{
\t\t\tisa = XCBuildConfiguration;
\t\t\tbuildSettings = {{
\t\t\t\tALWAYS_SEARCH_USER_PATHS = NO;
\t\t\t\tBUNDLE_LOADER = "$(TEST_HOST)";
\t\t\t\tCODE_SIGN_STYLE = Automatic;
\t\t\t\tCURRENT_PROJECT_VERSION = 1;
\t\t\t\tDEVELOPMENT_TEAM = {DEVELOPMENT_TEAM};
\t\t\t\tGENERATE_INFOPLIST_FILE = YES;
\t\t\t\tIPHONEOS_DEPLOYMENT_TARGET = 17.0;
\t\t\t\tMARKETING_VERSION = 1.0;
\t\t\t\tPRODUCT_BUNDLE_IDENTIFIER = com.yourcompany.babytreat.tests;
\t\t\t\tPRODUCT_NAME = "$(TARGET_NAME)";
\t\t\t\tSDKROOT = iphoneos;
\t\t\t\tSWIFT_EMIT_LOC_STRINGS = NO;
\t\t\t\tSWIFT_VERSION = 5.0;
\t\t\t\tTARGETED_DEVICE_FAMILY = "1,2";
\t\t\t\tTEST_HOST = "$(BUILT_PRODUCTS_DIR)/BabyTreat.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/BabyTreat";
\t\t\t}};
\t\t\tname = {config};
\t\t}};
"""


def main():
    src = open(PROJ).read()
    if TARGET_NAME in src:
        print("test target already present; nothing to do")
        return 0

    target = oid("target")
    product = oid("product")
    group = oid("group")
    sources_phase = oid("phase:sources")
    frameworks_phase = oid("phase:frameworks")
    resources_phase = oid("phase:resources")
    config_list = oid("configlist")
    dependency = oid("dependency")
    proxy = oid("proxy")

    file_refs, build_files, source_entries, group_children = [], [], [], []
    for name in SOURCES:
        fid, bid = oid("file:" + name), oid("build:" + name)
        file_refs.append(
            f'\t\t{fid} /* {name} */ = {{isa = PBXFileReference; '
            f'lastKnownFileType = sourcecode.swift; path = {name}; sourceTree = "<group>"; }};\n')
        build_files.append(
            f'\t\t{bid} /* {name} in Sources */ = {{isa = PBXBuildFile; fileRef = {fid} /* {name} */; }};\n')
        source_entries.append(f'\t\t\t\t{bid} /* {name} in Sources */,\n')
        group_children.append(f'\t\t\t\t{fid} /* {name} */,\n')

    src = insert_before(src, "/* End PBXBuildFile section */", "".join(build_files))

    file_refs.append(
        f'\t\t{product} /* {TARGET_NAME}.xctest */ = {{isa = PBXFileReference; '
        f'explicitFileType = wrapper.cfbundle; includeInIndex = 0; '
        f'path = {TARGET_NAME}.xctest; sourceTree = BUILT_PRODUCTS_DIR; }};\n')
    src = insert_before(src, "/* End PBXFileReference section */", "".join(file_refs))

    # Group for the test sources, plus the .xctest under Products.
    src = insert_before(src, "/* End PBXGroup section */",
                        f'\t\t{group} /* {TARGET_NAME} */ = {{\n\t\t\tisa = PBXGroup;\n\t\t\tchildren = (\n'
                        + "".join(group_children)
                        + f'\t\t\t);\n\t\t\tpath = {TARGET_NAME};\n\t\t\tsourceTree = "<group>";\n\t\t}};\n')

    def add_child(src, gid, line):
        # The root group carries no /* comment */, unlike every other group.
        pattern = re.compile(
            r'(\t\t' + gid + r'( /\* .*? \*/)? = \{\n\t\t\tisa = PBXGroup;\n\t\t\tchildren = \(\n)')
        out, count = pattern.subn(lambda m: m.group(1) + line, src, count=1)
        if count != 1:
            raise SystemExit(f"failed to attach child to group {gid}")
        return out

    src = add_child(src, MAIN_GROUP, f'\t\t\t\t{group} /* {TARGET_NAME} */,\n')
    src = add_child(src, PRODUCTS_GROUP, f'\t\t\t\t{product} /* {TARGET_NAME}.xctest */,\n')

    src = insert_before(src, "/* End PBXSourcesBuildPhase section */",
                        f'\t\t{sources_phase} /* Sources */ = {{\n\t\t\tisa = PBXSourcesBuildPhase;\n'
                        f'\t\t\tbuildActionMask = 2147483647;\n\t\t\tfiles = (\n'
                        + "".join(source_entries)
                        + '\t\t\t);\n\t\t\trunOnlyForDeploymentPostprocessing = 0;\n\t\t}};\n'.replace("}};", "};"))

    src = insert_before(src, "/* End PBXFrameworksBuildPhase section */",
                        f'\t\t{frameworks_phase} /* Frameworks */ = {{\n\t\t\tisa = PBXFrameworksBuildPhase;\n'
                        f'\t\t\tbuildActionMask = 2147483647;\n\t\t\tfiles = (\n\t\t\t);\n'
                        f'\t\t\trunOnlyForDeploymentPostprocessing = 0;\n\t\t}};\n')

    src = insert_before(src, "/* End PBXResourcesBuildPhase section */",
                        f'\t\t{resources_phase} /* Resources */ = {{\n\t\t\tisa = PBXResourcesBuildPhase;\n'
                        f'\t\t\tbuildActionMask = 2147483647;\n\t\t\tfiles = (\n\t\t\t);\n'
                        f'\t\t\trunOnlyForDeploymentPostprocessing = 0;\n\t\t}};\n')

    src = insert_before(src, "/* End XCBuildConfiguration section */",
                        build_settings("Debug") + build_settings("Release"))

    src = insert_before(src, "/* End XCConfigurationList section */",
                        f'\t\t{config_list} /* Build configuration list for PBXNativeTarget "{TARGET_NAME}" */ = {{\n'
                        f'\t\t\tisa = XCConfigurationList;\n\t\t\tbuildConfigurations = (\n'
                        f'\t\t\t\t{oid("config:Debug")} /* Debug */,\n'
                        f'\t\t\t\t{oid("config:Release")} /* Release */,\n'
                        f'\t\t\t);\n\t\t\tdefaultConfigurationIsVisible = 0;\n'
                        f'\t\t\tdefaultConfigurationName = Release;\n\t\t}};\n')

    # The test bundle is loaded into the app, so it must build after it.
    proxy_block = (f'\t\t{proxy} /* PBXContainerItemProxy */ = {{\n\t\t\tisa = PBXContainerItemProxy;\n'
                   f'\t\t\tcontainerPortal = {PROJECT_OBJ} /* Project object */;\n'
                   f'\t\t\tproxyType = 1;\n\t\t\tremoteGlobalIDString = {APP_TARGET};\n'
                   f'\t\t\tremoteInfo = BabyTreat;\n\t\t}};\n')
    if "/* Begin PBXContainerItemProxy section */" in src:
        src = insert_before(src, "/* End PBXContainerItemProxy section */", proxy_block)
    else:
        src = insert_before(src, "/* Begin PBXFileReference section */",
                            "/* Begin PBXContainerItemProxy section */\n" + proxy_block
                            + "/* End PBXContainerItemProxy section */\n\n")

    dep_block = (f'\t\t{dependency} /* PBXTargetDependency */ = {{\n\t\t\tisa = PBXTargetDependency;\n'
                 f'\t\t\ttarget = {APP_TARGET} /* BabyTreat */;\n'
                 f'\t\t\ttargetProxy = {proxy} /* PBXContainerItemProxy */;\n\t\t}};\n')
    if "/* Begin PBXTargetDependency section */" in src:
        src = insert_before(src, "/* End PBXTargetDependency section */", dep_block)
    else:
        src = insert_before(src, "/* Begin XCBuildConfiguration section */",
                            "/* Begin PBXTargetDependency section */\n" + dep_block
                            + "/* End PBXTargetDependency section */\n\n")

    src = insert_before(src, "/* End PBXNativeTarget section */",
                        f'\t\t{target} /* {TARGET_NAME} */ = {{\n\t\t\tisa = PBXNativeTarget;\n'
                        f'\t\t\tbuildConfigurationList = {config_list} /* Build configuration list for PBXNativeTarget "{TARGET_NAME}" */;\n'
                        f'\t\t\tbuildPhases = (\n\t\t\t\t{sources_phase} /* Sources */,\n'
                        f'\t\t\t\t{frameworks_phase} /* Frameworks */,\n'
                        f'\t\t\t\t{resources_phase} /* Resources */,\n\t\t\t);\n'
                        f'\t\t\tbuildRules = (\n\t\t\t);\n'
                        f'\t\t\tdependencies = (\n\t\t\t\t{dependency} /* PBXTargetDependency */,\n\t\t\t);\n'
                        f'\t\t\tname = {TARGET_NAME};\n\t\t\tproductName = {TARGET_NAME};\n'
                        f'\t\t\tproductReference = {product} /* {TARGET_NAME}.xctest */;\n'
                        f'\t\t\tproductType = "com.apple.product-type.bundle.unit-test";\n\t\t}};\n')

    src = src.replace(f'\t\t\t\t{APP_TARGET} /* BabyTreat */,\n\t\t\t);',
                      f'\t\t\t\t{APP_TARGET} /* BabyTreat */,\n\t\t\t\t{target} /* {TARGET_NAME} */,\n\t\t\t);', 1)

    open(PROJ, "w").write(src)
    lint = subprocess.run(["plutil", "-lint", PROJ], capture_output=True, text=True)
    if lint.returncode != 0:
        print(lint.stdout + lint.stderr, file=sys.stderr)
        return 1

    # Scheme: without a Testable entry `xcodebuild test` finds nothing to run.
    scheme = open(SCHEME).read()
    if TARGET_NAME not in scheme:
        testable = (f'         <TestableReference\n            skipped = "NO">\n'
                    f'            <BuildableReference\n'
                    f'               BuildableIdentifier = "primary"\n'
                    f'               BlueprintIdentifier = "{target}"\n'
                    f'               BuildableName = "{TARGET_NAME}.xctest"\n'
                    f'               BlueprintName = "{TARGET_NAME}"\n'
                    f'               ReferencedContainer = "container:BabyTreat.xcodeproj">\n'
                    f'            </BuildableReference>\n         </TestableReference>\n')
        scheme = scheme.replace("      </Testables>", testable + "      </Testables>", 1)
        open(SCHEME, "w").write(scheme)

    print(f"added target {TARGET_NAME} with {len(SOURCES)} source file(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
